import { ITrending } from './reducer'

export enum TYPE {
  TRENDING_COLLECTION_PENDING = 'TRENDING_COLLECTION_PENDING',
  TRENDING_COLLECTION_FAIL = 'TRENDING_COLLECTION_FAIL',
  GET_TRENDING_COLLECTION_ALL = 'GET_TRENDING_COLLECTION_ALL',
}

interface TRENDING_COLLECTION_PENDING {
  type: TYPE.TRENDING_COLLECTION_PENDING
}

interface TRENDING_COLLECTION_FAIL {
  type: TYPE.TRENDING_COLLECTION_FAIL
  payload: string
}

interface GET_TRENDING_COLLECTION_ALL {
  type: TYPE.GET_TRENDING_COLLECTION_ALL
  payload: ITrending[]
  total: number
}

export type Action = TRENDING_COLLECTION_PENDING | TRENDING_COLLECTION_FAIL | GET_TRENDING_COLLECTION_ALL
